### PR TITLE
Fixed erroneous approximation caused by using non-unbiased version of variance in TLS 

### PR DESCRIPTION
**Pull request by uriba**
TLS used covar, which divides by n-1 to achieve non-biased estimation, on one hand, but S.variance, which divides by n, on the other.
As a result there was some error emerging in the parameters estimation.
Switching to S.varianceUnbiased solved the issue.

### CODE REVIEW

**Comment by alpmestan** [comment]
Thanks a lot, glad you could find the issue so quickly! I think I will release 0.2.2 today.

**Comment by uriba** [comment]
Excellent, many thanks for the review.

Next thing will probably be robust fits and outliers detection, though that
will be more challenging and is of lesser priority to me now, so it'll
probably take a while.
If you happen to have a good reference for an easy to implement
statistically/academically popular robust fit algorithm I'll be happy to
use it (again - this is not exactly my field of expertise, though I have
some references to start with).

Take care,
Uri

**Comment by alpmestan** [comment]
This isn't my field neither. This library was born with me toying around for fun - I'm more a pure math kind of guy (I study pure math). So I don't happen to have such papers around (yet). I have released 0.2.2. Keep me posted for any improvements you want to do, feel free to email me and discuss stuffs with me, I'd be happy to help.

**Comment by uriba** [comment]
Will do.
Thanks again,

**Pull request merged**
