### PR TITLE
Added Total Least Squares suppor

### PR DESCRIPTION
**Pull request by uriba**
Hi,
I've added support for Total Least Squares that allows for regression over data for which both xs and ys may have errors in them.
Also made some refactoring to eliminate duplicated code and updated the tests.
As the test shows, the new function has some rounding issues (probably due to Double's limited accuracy, though I'm not sure). 
It'd be great if you could come up with a solution for that. Otherwise I think it performs pretty well.
Cheers,

### CODE REVIEW

**Comment by alpmestan** [comment]
Hi,

Thanks for your work on this library! Just a quick question: why not stick with 0.2.2? AFAICT, you basically add the TLS version of linear regression, which shouldn't cause a major version bump...?

I'll nonetheless merge and (unless i'm mistaken -- waiting for your motivation for bumping to 0.3 before doing that) change the version number, and also take a look at this rounding issue.

**Comment by uriba** [comment]
Hi,
Thanks for the quick response and the merge.

I'm not sure whether this is good enough a reason to bump the version. My instinct was that, as a new exported function is added, packages that depend on this function should not make the mistake of depending on >=0.2.*
However my experience in packages, versioning (as well as in Haskell in general) is quite limited so I think your instincts will be better than mine. Therefore, feel free to set the version number as you see fit. It'll sure be a better decision than mine.

Thanks and have a nice day,

**Comment by uriba** [comment]
BTW, a short description of TLS, should you need one, can be found here:
http://www.dspcsp.com/pubs/euclreg.pdf
Cheers,
Uri

**Comment by alpmestan** [comment]
I'll reread the PVP and see what's best for us. I'll try to release your work this week. Thanks again for this, and for the paper.

**Comment by uriba** [comment]
I was unaware of this document (the pvp).
Following its guidelines I think increasing the minor number is what is
probably best.
Thanks again,
Uri

**Comment by alpmestan** [comment]
Wow, the TLS version indeed is really off for the 'alpha' coefficient! I don't think Double's inaccuracy can be the cause -- Double's inaccuracy is what causes my tests to be off by 0.000001 or smth like that from the actual coefficients, but here I see the TLS version being off by 150 and more ; could you check throroughly your implementation? If you find something feel free to open a new pull request. In the meantime, the release of 0.2.2 is on hold.

**Comment by uriba** [comment]
Hi again,

The reason is indeed not Double's accuracy but a different one with which
I'd be happy to get your input.

The implementation of covar divides by (n-1) in order to get an unbiased
estimate.
This in turn (as far as I understand, statistics is not my strongest field)
results in the parameters being adjusted to the unbiased covar value and
not the "real" value reflected by the input.

In the case of TLS the adjustment (which in this case is actually an error)
in the slope is ~ 0.000001 (whereas in the regular LS it is 5 orders of
magnitude smaller!).
Given that the data itself is located at ~ 10000000 and that the line
passes through the "center of mass" in both cases, the resulting impact on
the alpha coefficient is quite large (depending on what you're comparing
to, relative to the scale of the data it isn't though it is much worse than
LS's performance in this case).

Replacing the denominator in covar's calculation solves the problem in the
test but will probably give inferior results with "real" data.
I'm attaching a code snippet and the result of running the test with it to
demonstrate the point though you might want to test it out yourself.

Will be happy to know what you think will best resolve this issue.

Have a nice day,
Uri

## ----------------------------------------------------- the code

linearRegressionTLS' :: S.Sample -> S.Sample -> (Double,Double)
linearRegressionTLS' xs ys = (alpha, beta)
    where
          !c                   = covar'
          !b                   = (S.variance xs - (S.variance ys)) / c
          !m1                  = S.mean xs
          !m2                  = S.mean ys
          !betas               = [(-b - sqrt(b^2+4))/2,(-b + sqrt(b^2+4))
/2]
          !beta                = if c > 0 then maximum betas else minimum
betas
          !alpha               = m2 - beta \* m1
          !covar'              = U.sum (U.zipWith (*) (U.map (subtract m1)
xs) (U.map (subtract m2) ys)) / n
          !n = fromIntegral $ U.length xs

--------------------------------------- results in the following when
running the test -------------------
linearRegression:
(2000.0000939064194,99.99999999999373)
linearRegressionTLS:
(2000.0000281374669,99.99999999999812)
linearRegression:
(2000.0001565108541,99.99999999999373)
linearRegressionTLS:
(2000.000046895817,99.99999999999812)
linearRegression:
(2000.000219115056,99.99999999999373)
linearRegressionTLS:
(2000.0000656540506,99.99999999999812)
linearRegression:
(2000.0002817194909,99.99999999999373)
linearRegressionTLS:
(2000.0000844122842,99.99999999999812)
linearRegression:
(2000.00034432346,99.99999999999373)
linearRegressionTLS:
(2000.0001031709835,99.99999999999812)
linearRegression:
(2000.0004069278948,99.99999999999373)
linearRegressionTLS:
(2000.0001219292171,99.99999999999812)
linearRegression:
(2000.0004695323296,99.99999999999373)
linearRegressionTLS:
(2000.0001406874508,99.99999999999812)
linearRegression:
(2000.0005321362987,99.99999999999373)
linearRegressionTLS:
(2000.0001594456844,99.99999999999812)
linearRegression:
(2000.0005947407335,99.99999999999373)
linearRegressionTLS:
(2000.000178203918,99.99999999999812)
linearRegression:
(2000.0006573451683,99.99999999999373)
linearRegressionTLS:

## (2000.0001969626173,99.99999999999812)

**Comment by uriba** [comment]
Actually the entire issue can be very easily resolved by using
varianceUnbiased instead of variance it TLS's implementation.
I'll update the code shortly and submit a pull request.
Cheers,
Uri

**Pull request merged**
